### PR TITLE
Fix#64: The application crashes on the second commit&push

### LINKED ISSUE #64: 2nd push causing crashes
2nd time pushing is causing app to crash

## steps to reproduce
1. commit
2. push
3. commit
4. push

## suggested fix
The issue has something to do with authentication

### PR DESCRIPTION
**Pull request by Leon0315**
Added a constructor method to assign new copies of `cred` every time when required by calling the keyword `new`. This now will allow users to commit and push second time without crashing application. Fix #64

### CODE REVIEW

**Review by aujlarj — APPROVED** [review]
**Does the code work?** Yes
**Did I test it locally?** Yes
**What OS am I using?** Windows 10
**Does it perform its intended function, the logic is correct etc.**
Works perfect, didn't crash on 2nd or more commit-> push
**Is the code well documented? Would it be easily understood to other developers?**
Yes, the comments explain the functions below
**Does it have correct linting/formatting?**
The formate looks good.
**Is there any redundant or duplicate code? Any hard-coded values?**
I didn't find any duplicate code.
**Can any of the code be replaced with library functions?**
N/A
**Are good names used for methods, variables, etc.? Do they follow naming conventions?**
Yes, the variables are reused and new ones are named accordingly
**Were any other issues found?**
Not related to this issue.

**Review by c-renard — APPROVED** [review]
**Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.** Yes, I tested the code locally with Windows 10 it fixes the issue, I tried doing multiple iterations of the same steps with different numbers of commits and when switching between branches and these cases all functioned correctly

**Is the code well documented? Would it be easily understood to other developers?** Yes, comments explaining code where most changes are made

**Does it have correct linting/formatting?** Yes

**Is there any redundant or duplicate code? Any hard-coded values?** Some lines of coded are repeated in different areas but I don't think it is redundant

**Can any of the code be replaced with library functions?** Not that I am aware of

**Are good names used for methods, variables, etc.? Do they follow naming conventions?** Yes

**Were any other issues found?** Some blank nodes linger when doing iterations of commits of pushing but I think this may be caused by another issue

**Review by cchampernowne — APPROVED** [review]
Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.
- Yes. yes. Windows 10. Tested 3 commits and all worked. Logic seems sound. authentification information was being discarded after a push, now the information is retrieved for every new push.

Is the code well documented? Would it be easily understood to other developers?
- yes

Does it have correct linting/formatting?
- yes

Is there any redundant or duplicate code? Any hard-coded values?
- Not that i found

Can any of the code be replaced with library functions?
- no

Are good names used for methods, variables, etc.? Do they follow naming conventions?
- To my knowledge, yes

Were any other issues found?
- no

**Comment by mdesco18** [comment]
Has this been tested from outside the group yet?

Edit: okay i will after class

**Comment by Leon0315** [comment]
@mdesco18 not yet, still need 1 from outside group.

**Review by mdesco18 — APPROVED** [review]
**Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.**
Works on Windows 10. 3 commits and pushes were successful
**Is the code well documented? Would it be easily understood to other developers?**
Added code is clear and documented
**Does it have correct linting/formatting?**
Formatted well
**Is there any redundant or duplicate code? Any hard-coded values?**
No. Duplicate code in functions
**Can any of the code be replaced with library functions?**
No
**Are good names used for methods, variables, etc.? Do they follow naming conventions?**
Yes
**Were any other issues found?**
No

**Pull request merged**
