### PR TITLE
Fix Issue #31: Prevent craching when clicking push before commiting

### PR DESCRIPTION
**Pull request by smithmr**
## PR fixes 
1. crashing when clicking push before commiting by checking to see if there are any unpushed commits 
2. Notifying the user to commit before pushing.

## Issue discovered
- There is an issue where the app crashes if you commit->push->commit->push

### CODE REVIEW

**Review by Leon0315 — CHANGES_REQUESTED** [review]
**Does the code work?**: Yes, user cannot push without a commit now.
**Is the code well documented?**: No, add comments to code please.
**Does it have correct linting/formatting?**: Yes
**Is there any redundant or duplicate code? Any hard-coded values?**: No, the logic is pretty simple.
**Can any of the code be replaced with library functions?**: N/A
**Are good names used for methods, variables, etc.? Do they follow naming conventions?**: Yes, re-used the variable names from the original code.
**Were any other issues found?** : Yes, still will crash after 2nd commit push

**Comment by aujlarj** [comment]
The code works
No comments added but it is pretty straight forward to understand
Code is formatted
No hard coding
N/A
Yes
Yes, we did found one more issue, i.e. the app crashed after the second commit and push.

**Comment by aujlarj** [comment]
The code works
No comments added but it is pretty straight forward to understand
Code is formatted
No hard coding
N/A
Yes
Yes, we did found one more issue, i.e. the app crashed after the second commit and push.

**Review by aujlarj — COMMENTED** [review]
The code works
No comments added but it is pretty straight forward to understand
Code is formatted
No hard coding
N/A
Yes
Yes, we did found one more issue, i.e. the app crashed after the second commit and push.

**Review by aujlarj — APPROVED** [review]

**Review by aujlarj — APPROVED** [review]

**Review by Leon0315 — APPROVED** [review]

**Comment by smithmr** [comment]
> **Does the code work?**: Yes, user cannot push without a commit now.
> **Is the code well documented?**: No, add comments to code please.
> **Does it have correct linting/formatting?**: Yes
> **Is there any redundant or duplicate code? Any hard-coded values?**: No, the logic is pretty simple.
> **Can any of the code be replaced with library functions?**: N/A
> **Are good names used for methods, variables, etc.? Do they follow naming conventions?**: Yes, re-used the variable names from the original code.
> **Were any other issues found?** : Yes, it seems that when you do a second push without commit, it will still goes to black screen, but if reset the app, it will work again.

I am unable to replicate your comment here 'Yes, it seems that when you do a second push without commit, it will still goes to black screen, but if reset the app, it will work again.'.... You can click push over and over again, it will just pop up with the same notification.

**Pull request merged**
