### PR TITLE
Improving changed/staged file CSS

### PR DESCRIPTION
**Pull request by jbenning97**
### Changes made

* aligned checkbox to the right
* gave the checkbox a pointer cursor on hover
* replicated the styles of the changed files for the staged files
* added overall padding to the file panel

Before: 

Screen Shot 2019-06-15 at 1 32 48 PM

After:

Screen Shot 2019-06-15 at 1 57 07 PM (2)

### CODE REVIEW

**Review by Leon0315 — APPROVED** [review]
**Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.**
Yes, the checkbox is aligned properly and shows a cursor with hover on it. Tested on mac os 10.14. The logic is style fixes.

**Is the code well documented? Would it be easily understood to other developers?**
yes, just style fixes.
**Does it have correct linting/formatting?**
yes
**Is there any redundant or duplicate code? Any hard-coded values?**
no
**Can any of the code be replaced with library functions?**
no
**Are good names used for methods, variables, etc.? Do they follow naming conventions?**
yes
**Were any other issues found?**
no**

**Review by aujlarj — APPROVED** [review]
**Does the code work?** Yes
**Did I test it locally?** Yes
**What OS am I using?** Windows 10
**Does it perform its intended function, the logic is correct etc.**
Looks great, works well with resizing
**Is the code well documented? Would it be easily understood to other developers?**
Yes, where ever necessary 
**Does it have correct linting/formatting?**
Code formate looks good.
**Is there any redundant or duplicate code? Any hard-coded values?**
Nope
**Can any of the code be replaced with library functions?**
N/A
**Are good names used for methods, variables, etc.? Do they follow naming conventions?**
Yes
**Were any other issues found?**
No

**Comment by sinoyuhanxiao** [comment]
**Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.**
The code works. I test the code on windows 10. The logic is correct.
**Is the code well documented? Would it be easily understood to other developers?**
Simple stype fix. Easy to understand.
**Does it have correct linting/formatting?**
Yes
**Is there any redundant or duplicate code? Any hard-coded values?**
No redundant and hard-coded values. 
**Can any of the code be replaced with library functions?**
No
**Are good names used for methods, variables, etc.? Do they follow naming conventions?**
Yes, they follow naming conventions
**Were any other issues found?**
No

**Review by katland — APPROVED** [review]
**Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.**
Works on mac OS 10.13.
**Is the code well documented? Would it be easily understood to other developers?**
yes
**Does it have correct linting/formatting?**
yes
**Is there any redundant or duplicate code? Any hard-coded values?**
no
**Can any of the code be replaced with library functions?**
no
**Are good names used for methods, variables, etc.? Do they follow naming conventions?**
yes
**Were any other issues found?**
no

**Review by sinoyuhanxiao — APPROVED** [review]

**Review by c-renard — APPROVED** [review]
**Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc**.
Yes the code functions correctly on Windows 10
**Is the code well documented? Would it be easily understood to other developers?**
Yes
**Does it have correct linting/formatting?**
Yes
**Is there any redundant or duplicate code? Any hard-coded values?**
No
**Can any of the code be replaced with library functions?**
No
**Are good names used for methods, variables, etc.? Do they follow naming conventions?**
N/A
**Were any other issues found?**
No the code looks and functions great

**Pull request merged**
