### PR TITLE
Fix issue where create commit requires a tag name

### PR DESCRIPTION
**Pull request by zeshili**
This pull request is meant to resolve the bug where a user must provide a tag name in order to create a commit. The code changes in this pull request will ensure a user is able to create a commit with just a commit message and added files.

### CODE REVIEW

**Comment by smithmr** [comment]
Tested on MB PRO
- Does not fix the problem!
- Getting error that I cannot commit, and commit box is still not functioning
Screen Shot 2019-06-09 at 8 45 01 PM

**Comment by smithmr** [comment]
#### Does the code work? 
- yes it fixes the bug
#### Did I test it locally? 
- Tested on MB
#### Does it perform its intended function, the logic is correct etc.
- logic is correct
#### Is the code well documented?
- yes
#### Does it have correct linting/formatting?
- N/A
## Is there any redundant or duplicate code? Any hard-coded values?
- N/A
#### Can any of the code be replaced with library functions?
- N/A
 #### Are good names used for methods, variables, etc.? Do they follow naming conventions?
- N/A
#### Were any other issues found?
- NA

**Review by smithmr — APPROVED** [review]
#### Does the code work? 
- yes it fixes the bug
#### Did I test it locally? 
- Tested on MB
#### Does it perform its intended function, the logic is correct etc.
- logic is correct
#### Is the code well documented?
- yes
#### Does it have correct linting/formatting?
- N/A
#### Is there any redundant or duplicate code? Any hard-coded values?
- N/A
#### Can any of the code be replaced with library functions?
- N/A
 #### Are good names used for methods, variables, etc.? Do they follow naming conventions?
- N/A
#### Were any other issues found?
- NA

**Review by ajlarivi — APPROVED** [review]
#### Does the code work? 
- yes, the bug is fixed
#### Did I test it locally? 
- Tested on linux mint
#### Does it perform its intended function, the logic is correct etc.
- yes
#### Is the code well documented?
- yes
#### Does it have correct linting/formatting?
- N/A
#### Is there any redundant or duplicate code? Any hard-coded values?
- N/A
#### Can any of the code be replaced with library functions?
- N/A
 #### Are good names used for methods, variables, etc.? Do they follow naming conventions?
- N/A
#### Were any other issues found?
- NA

**Pull request merged**
