### PR TITLE
Partially implement issue 35/84: Improve stash: drop

### PR DESCRIPTION
**Pull request by mdesco18**
Follow-up from #102 

This branch has functionality that implements `git stash drop` from #35 and #84 

There are prototypes of branch and show existing in this branch but they are commented out until full implementation. 

Test its functionality by dropping stashes from the stash list in the stash modal and check if it was successful from the command line or in the VisGit tree

This branch also contains the updated stash modal, a hotfix for the recent repository display, and a hotfix for properly updating the event/error modal for git actions

**To review**: Create a stash entry and drop it. Confirm with the command line `git stash list` and working tree (stashed node should be gone and stash modal list should be updated accordingly)

### CODE REVIEW

**Comment by smithmr** [comment]
@mdesco18 not sure how to test this? can you list some stuff you want me to test with the desired outcome... there is a lot going on with the modal lol.

**Comment by mdesco18** [comment]
> @mdesco18 not sure how to test this? can you list some stuff you want me to test with the desired outcome... there is a lot going on with the modal lol.

Create a stash entry and drop it. Confirm with the command line and working tree.

**Review by jbenning97 — APPROVED** [review]
**Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.**

Yes, tested on macOS High Sierra 10.13.3, dropping is now working

**Is the code well documented? Would it be easily understood to other developers?**

yes, appropriate documentation/comments

**Does it have correct linting/formatting?**

Yes

**Is there any redundant or duplicate code? Any hard-coded values?**

No

**Can any of the code be replaced with library functions?**

No

**Are good names used for methods, variables, etc.? Do they follow naming conventions?**

Yes

**Were any other issues found?**

Not that I could find, good implementation 👍

**Review by sinoyuhanxiao — APPROVED** [review]
**Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.**
The code works, I tested that on Windows 10. It performs the intended function with correct logic.
**Is the code well documented? Would it be easily understood to other developers?**
Yes they are well documented and can be understood.
**Does it have correct linting/formatting?**
Yes
**Is there any redundant or duplicate code? Any hard-coded values?**
No redundant and hard codes
**Can any of the code be replaced with library functions?**
No
**Are good names used for methods, variables, etc.? Do they follow naming conventions?**
Yes all followed conventions
**Were any other issues found?**
No other issues found

**Review by Leon0315 — APPROVED** [review]
**Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.**
Yes, tested on Mac OS 10.14. The stash was dropped successfully and matched the command line result.

**Is the code well documented? Would it be easily understood to other developers?**
Yes, good comments in the code.

**Does it have correct linting/formatting?**
Yes

**Is there any redundant or duplicate code? Any hard-coded values?**
No, didn't find any. 

**Can any of the code be replaced with library functions?**
N/A

**Are good names used for methods, variables, etc.? Do they follow naming conventions?**
Yes, method names are straightforward.

**Were any other issues found?**
No.

**Pull request merged**
