### PR TITLE
removed pushing to origin for every push.

### LINKED ISSUE #81: Pushing to origin every push.
The push function is pushing with `addCommand("git push -u origin " + branch);` every push, 

This functionality should be separated from the push button or only push like that when the branch does not exist in origin.

### PR DESCRIPTION
**Pull request by smithmr**
### Fixes
- pushing creating upstream branch every push
- waits to update the graph before showing success modal
- Checking the DOM for the branch name

## new functions
- Added getBranchName(), which uses NodeGit to get the branch name rather than the DOM

## Updates
- fixed all the functions in .git to call getBranchName() instead of calling the DOM
closes #81

### CODE REVIEW

**Comment by cchampernowne** [comment]
what test cases would you like us to do? Just push to existing branch?

**Comment by smithmr** [comment]
> what test cases would you like us to do? Just push to existing branch?

Pushing is fine.

**Comment by Leon0315** [comment]
Screen Shot 2019-06-10 at 9 13 13 PM
It seems that it still pushes to origin every time, but it should't right?

**Comment by cchampernowne** [comment]
Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.
-Yes. tested locally on Windows 10. performs intended function. changes flow from pushing to origin for each push, to checking if origin exist/if ahead of origin -> "git push" if origin exists and current branch is ahead of remote

Is the code well documented? Would it be easily understood to other developers?
- good comments, names of variables/functions etc are well named

Does it have correct linting/formatting?
- yes

Is there any redundant or duplicate code? Any hard-coded values?
- Not in matts branch. However, I had to hard code in some values related to a separate issue #101 which caused my machine to not recognize remote repos

Can any of the code be replaced with library functions?
-no

Are good names used for methods, variables, etc.? Do they follow naming conventions?
-yes

Were any other issues found?
-no

**Review by cchampernowne — APPROVED** [review]
Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.
- Yes. tested locally on Windows 10. performs intended function. changes flow from pushing to origin for each push, to checking if origin exist/if ahead of origin -> "git push" if origin exists and current branch is ahead of remote

Is the code well documented? Would it be easily understood to other developers?
- good comments, names of variables/functions etc are well named

Does it have correct linting/formatting?
- yes

Is there any redundant or duplicate code? Any hard-coded values?
- Not in matts branch. However, I had to hard code in some values related to a separate issue #101 which caused my machine to not recognize remote repos

Can any of the code be replaced with library functions?
- no

Are good names used for methods, variables, etc.? Do they follow naming conventions?
- yes

Were any other issues found?
- no

**Comment by smithmr** [comment]
> Screen Shot 2019-06-10 at 9 13 13 PM
> 
> It seems that it still pushes to origin every time, but it should't right?

I think you are testing on the wrong branch.

Screen Shot 2019-06-11 at 10 15 38 AM

@Leon0315

**Review by Leon0315 — APPROVED** [review]
**Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.**

Yes. tested locally on Mac Mojave. Now for every push it won't push to origin anymore. The logic is to check if there is a remote branch first, if there is, push without origin option.

**Is the code well documented? Would it be easily understood to other developers?**
yes, I can see comments for every new functions.

**Does it have correct linting/formatting?**
Yes.

**Is there any redundant or duplicate code? Any hard-coded values?**
No.

**Can any of the code be replaced with library functions?**
No.

**Are good names used for methods, variables, etc.? Do they follow naming conventions?**

yes

**Were any other issues found?**
No

**Pull request merged**
