### PR TITLE
WIP: Implement Issue #35: Add stashing and applying functionality

### PR DESCRIPTION
**Pull request by mdesco18**
This enhancement (#35) implements the following **git stash** functionalities:

- git stash push -m `message`
- git stash push --untracked
- git stash push --keep-index
- git stash pop --index [n]
- git stash apply --index [n]
- git stash drop --index [n]
- git stash list

**Future implementation**: git stash branch <branchname> <stash>
NodeGit API currently does not support this function. Therefore, a pop or commit with checkout could simulate this function but more research is required so that issue is too large for this sprint.  

NodeGit API requires a message for Stashes therefore they will be named "On branch: message" instead of "WIP on branch: commit-head commit-message"

NodeGit seems to recognize a merge conflict for any kind of change to the working directory. Therefore, if you are applying a stash to a clean working directory, it may still say there are conflicts from new, untracked files. However, if the merge is safe, the files without conflicts will still be applied to the working directory. 
If anybody has found mergeFlags or checkoutOptions with nodegit.Merge.merge that do not result in these kinds of conflicts, please commit them. Because of the conflicts, the index tree currently will not update the stash nodes. 

Stash and Pop functionalities can be accessed from buttons beneath the `filePanel`.

[**WIP**] The Stash button in the NavBar will display a window that lists your stashes from the array `stashHistory` with the most recent displayed first and buttons to perform all the stash functionalities above. [Done]

**Function Descriptions:**

- _addAndStash_(options): stages files in the index tree and stashes the working directory with the given message from commit-message-input panel. Options are passed as a parameter depending on which button is pressed
- _popStash_(index): pops the stash at the given index and tries to merge into the working directory. Fails if merge conflicts exist but will still apply the stash safely. Index is passed as a parameter depending on which stash is selected when the button is pushed. 
- _applyStash_(index): similar to _popStash_ but does not remove the stash from the list
- _dropStash_(index): removes the stash at the given index and updates the index tree 

**WIP: GUI popup window almost finished** [Done]

**WIP: Further testing still required on**
- untracked option [Done]
- keep index option [Done]
- drop [Currently non-functioning]
- refresh index tree [Not implemented]

**REVIEWERS**
This is a large enhancement and will require some time to review and test. For now, the requirements of the issue are finished and ready to demo. Reviewers can use the buttons underneath the `filePanel` to test `git stash push -m` and `git stash pop` to test the enhancements functionality for now or wait until tonight to test it in full. Otherwise, a code review of the files changed would be appreciated. @mdesco18 for clarifications or suggest code //comments

**EDIT UPDATE**
The code that will be merged into master has updated the WIP status of this issue. See above.

### CODE REVIEW

**Review by ajlarivi — COMMENTED** [review]
**Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.**

Running linux mint I was able to test and confirm local functionality of:
- git stash push -m
- git stash pop

**Is the code well documented? Would it be easily understood to other developers?**
code is well documented, comments at the beginning of each function, to-do's clearly marked, strong naming convention. 

**Does it have correct linting/formatting?**
linting and formatting good, code is clear and readable. 

**Is there any redundant or duplicate code? Any hard-coded values?**
none found.

**Can any of the code be replaced with library functions?**
None found

**Are good names used for methods, variables, etc.? Do they follow naming conventions?**
function names are clear, proper convention followed.

Were any other issues found?
I encountered issue with the styling, it seems on my machine the commit button gets cut off and issues button goes overtop of the logs. This could be unique to my machine though as I have all kinds of styling issues, seems to be a thing with the application window on my OS.
issue35

**Review by rhyslawsn — APPROVED** [review]
OS used during testing: Windows 10

### Is the code well documented? Would it be easily understood to other developers?
The code has comments at the beginning of the functions outlining what each one does. There could be more comments inside the actual functions, but it's pretty easy to figure out which line does what.

### Does it have correct linting/formatting?
The code is **very** readable and formatting is consistent with the rest of the files.

### Is there any redundant or duplicate code? Any hard-coded values?
No.

### Can any of the code be replaced with library functions?
No.

### Are good names used for methods, variables, etc.? Do they follow naming conventions?
Function names are very clear.

### Were any other issues found?
Some responsiveness issues were found with the buttons (refer to screenshot below) plus stash button in navbar is not functional.
image

**Comment by mdesco18** [comment]
The styling issues are fixed with the merger of issue #3/pull request #75! Thanks for the reviews.

**Review by ajlarivi — APPROVED** [review]
> **Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.**
> 
> Running linux mint I was able to test and confirm local functionality of:
> 
> * git stash push -m
> * git stash pop
> 
> **Is the code well documented? Would it be easily understood to other developers?**
> code is well documented, comments at the beginning of each function, to-do's clearly marked, strong naming convention.
> 
> **Does it have correct linting/formatting?**
> linting and formatting good, code is clear and readable.
> 
> **Is there any redundant or duplicate code? Any hard-coded values?**
> none found.
> 
> **Can any of the code be replaced with library functions?**
> None found
> 
> **Are good names used for methods, variables, etc.? Do they follow naming conventions?**
> function names are clear, proper convention followed.
> 
> Were any other issues found?
> I encountered issue with the styling, it seems on my machine the commit button gets cut off and issues button goes overtop of the logs. This could be unique to my machine though as I have all kinds of styling issues, seems to be a thing with the application window on my OS.
> issue35

as per Marks comment:
> The styling issues are fixed with the merger of issue #3/pull request #75! Thanks for the reviews.

Approving PR.

**Comment by mdesco18** [comment]
Great work on this guys!

**Pull request merged**
