### PR TITLE
Push to origin, Pull from origin, status update fix

### LINKED ISSUE #103: Pull does not update git status correctly
Currently when pulling, visual git does not properly update your git status. 

**steps to reproduce:**
- perform a change on the remote repo
- perform a pull in visualGit
- run `git status` in your command line

Changes are indeed pulled and files are updated, however git does not recognise that a pull has occurred. Git status will report that the remote is still ahead and visual git will think that the changes induced by the pull are local changes that can be staged and committed.

### PR DESCRIPTION
**Pull request by smithmr**
Fixed pull function.
Fixed get status function.
Re-added code from merge mess ups.

## to test
1. On your terminal, `git checkout -b {new_branch}` 
2. `npm install` then `npm start`
3. open the repo that the test branch was created on. THIS HAS TO BE A REAL REPO THAT IS ON GITHUB NOT SOME DUMMY REPO YOU CREATED BUT IS NOT ON GITHUB.
4. click push -> modal should appear to create the upstream branch. PRESS CANCEL DONT PUSH IT YET
5. Check that the status in bottom right says "remote does not exist"
6. Press Pull, Modal should appear saying remote does not exist.
7. Click push again and push it upstream. Now WAIT, the modal will change. 
8. go to the repo on github and see if the branch is on there now
9. go to terminal and type `git status`, should be up to date with origin {branch_name}

## This may not work on windows but try it anyway!
- a known issue is that nodeGit is not working properly on windows.

closes #103 #101 #89

### CODE REVIEW

**Review by jbenning97 — APPROVED** [review]
* Tested on macOS 10.14

* Followed all of the steps and works exactly how it is described in PR

* Tried again, for reassurance, and works 👍

**Comment by zeshili** [comment]
- Tested on macOS 10.14
- Does not work for me when I try to pull as I get this screen.
Screen Shot 2019-06-25 at 4 50 19 PM
- Does not work for me when I try to push as I get stuck on this modal
Screen Shot 2019-06-25 at 4 49 52 PM

**Comment by cchampernowne** [comment]
Tested on Ubuntu 14.04

Works for all provided test cases

additionally, I tested fetching, then pulling from a remote repo that is ahead which also worked

Ty Matt!

**Review by cchampernowne — APPROVED** [review]
Tested on Ubuntu 14.04

Works for all provided test cases

additionally, I tested fetching, then pulling from a remote repo that is ahead which also worked

Ty Matt!

**Comment by AhmadAlsaif** [comment]
* Testing it on Mac 10.14
* Following the testing steps mentioned above, everything works as mentioned. However, step#8 didn't work for me. I couldn't see the created branch in Github. 

Screen Shot 1440-10-22 at 5 19 53 PM

Screen Shot 1440-10-22 at 4 53 45 PM

Screen Shot 1440-10-22 at 4 53 57 PM

Note: we probably need more reviewers on this since the issue might be related to my testing repo.

**Pull request merged**
