### PR TITLE
Fix Issues #85, #87:  adding and modifying a tag to a preexisting commit

### PR DESCRIPTION
**Pull request by AhmadAlsaif**
#### 1. The ability to add a tag to a preexisting commit

Screen Shot 1440-10-06 at 11 09 48 PM

#### 2. The ability to modify a preexisting tag

Screen Shot 1440-10-06 at 11 12 53 PM

A user now can navigate to a commit node on the graph, at any level, and after clicking on the node, it will show a tag name field and tag message beside each commit. The user can now add a tag to a preexisting commit and modify it as well. 

Note:

- Tag names can't include any spaces
- Tag messages are optional
- When the graph is zoomed in at the lowest level, each graph node represent one commit

### CODE REVIEW

**Review by SrishtiSinghal — COMMENTED** [review]
- I pulled the branch locally and the code works perfectly on my Mac version 10.13.6. 

- The code is well documented with sufficient comments 

- The variable names are appropriate and there's no hard coded values. 

Overall, the code performs the intended task of adding and modifying a tag to a preexisting commit

**Review by jamshale — APPROVED** [review]
**Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.**
Using windows 10. The add/modify/delete works as it should. Commits appear to match the clickedd node 

**Is the code well documented? Would it be easily understood to other developers?**
Yes

**Does it have correct linting/formatting?**
Yes

**Is there any redundant or duplicate code? Any hard-coded values?**
Didn't find any hard-coded values. Didn't detect duplicated code

**Can any of the code be replaced with library functions?**
Makes use of nodegit extensively. 

**Are good names used for methods, variables, etc.? Do they follow naming conventions?**
The naming convention was well done

**Were any other issues found?**
It didn't initially work for repos already on my local hard drive. It worked if I recloned the repo. Should the modal close after clicking an add/modify/delete button? If the field is unchanged add/modify should not be clickable

**Comment by SrishtiSinghal** [comment]
I pulled the branch locally and the code works perfectly on my Mac version 10.13.6.

The code is well documented with sufficient comments

The variable names are appropriate and there's no hard coded values.

Overall, the code performs the intended task of adding and modifying a tag to a preexisting commit

**Comment by SrishtiSinghal** [comment]
- I pulled the branch locally and the code works perfectly on my Mac version 10.13.6. 

- The code is well documented with sufficient comments 

- The variable names are appropriate and there's no hard coded values. 

Overall, the code performs the intended task of adding and modifying a tag to a preexisting commit

**Review by SrishtiSinghal — APPROVED** [review]
I pulled the branch locally and the code works perfectly on my Mac version 10.13.6.

The code is well documented with sufficient comments

The variable names are appropriate and there's no hard coded values.

Overall, the code performs the intended task of adding and modifying a tag to a preexisting commit

**Pull request merged**
