### PR TITLE
Issue62 tag hover final

### PR DESCRIPTION
**Pull request by csamcharles**
# Adding Tag Hover Functionality
Have rebased with the current master and everything looks like its working on my machine (Win 10 Pro).

## Instructions to test
1. Run npm install just in case
2. Load repo
3. Zoom in to lowest level of nodes
4. If there are tags on commits, they should show up on hover.
5. Test add/modify/delete of tags and make sure the on hover reflects the changes
6. Look for any unexpected behavious

Thanks!

### CODE REVIEW

**Comment by jbenning97** [comment]
* Testing on macOS 10.13. 

* Tags displaying on hover

* Tags being added and deleted properly, along with a graph refresh

* Tags being properly, along with a graph refresh

*  Graph not updating after a tag modification. However tag is modified upon refresh

**Comment by mdesco18** [comment]
Remove token.json

**Comment by mdesco18** [comment]
Also this PR looks like it includes the hotfix #127. Please confirm this by testing for it

**Review by jbenning97 — COMMENTED** [review]
* After most recent changes, adding, deleting, modifying, hovering over tags now works and graph updates correctly

* Only changes that I would suggest is having a fallback when a user clicks 'Delete' tag when no tag exists, but that can be a separate issue

* Will approve when it's approved by others, for safety

**Comment by csamcharles** [comment]
> Also this PR looks like it includes the hotfix #127. Please confirm this by testing for it

I think it should include all features so far right since I merged the most current master... Am I misunderstanding our process?

**Comment by csamcharles** [comment]
> Remove token.json

done!

**Comment by csamcharles** [comment]
> * After most recent changes, adding, deleting, modifying, hovering over tags now works and graph updates correctly
> * Only changes that I would suggest is having a fallback when a user clicks 'Delete' tag when no tag exists, but that can be a separate issue
> * Will approve when it's approved by others, for safety

I have just pushed a new commit that removes the delete button if there is no tag to delete. Good catch!

**Review by jbenning97 — APPROVED** [review]

**Comment by Leon0315** [comment]
Will the initial tag always be there in the "commit history" after deletion? Tested hover, add/ modify/ delete, hover works well, the graph updates accordingly.

Screen Shot 2019-06-24 at 1 35 44 PM

**Comment by jamshale** [comment]
Every commit in history will show and you can add a tag to any commit in history at any point

**Review by Leon0315 — APPROVED** [review]

**Review by jamshale — APPROVED** [review]

**Review by AhmadAlsaif — APPROVED** [review]
* Testing on macOS 10.14.5

* Tags are displayed on hover and correspond to modification and deletion

* adding, modifying and deleting tags works properly

* code is well written and has adequate comments!

**Pull request merged**
