### PR TITLE
Revert "Implemented: Fix to 89, 101"

### PR DESCRIPTION
**Pull request by mdesco18**
Reverts uvicgse/project-virtual-team-2#137

getAheadBehind not implemented properly

This is breaking Push and Pull on Windows and features such as amendCommit and fetch status

Testing is required on branch master from users on all machines. 
The PR will be ready for review to revert once a consensus has been agreed on the status of master

@smithmr : Mac - working
@mdesco18 : Windows - broken
@c-renard  : Windows - broken
@Leon0315 : Mac - working

### CODE REVIEW

**Comment by cchampernowne** [comment]
I tested on linux and it is working

**Comment by aujlarj** [comment]
Tested it on Windows 10. Push/Pull doesn't work

**Comment by smithmr** [comment]
@mdesco18 Can we create a new issue to fix the problem rather than revert the branch?

**Comment by mdesco18** [comment]
> @mdesco18 Can we create a new issue to fix the problem rather than revert the branch?

Before the PRs in the queue can be tested either the issue needs to be fixed or the branch is reverted. 
This bug doesn't affect the functionality as far as I know of any of the features to be merged but they cannot be tested in this state. 

It is up to the team to decide which they'd rather do. That is why this PR is drafted.

@smithmr I agree that it would be annoying to revert again at this point but we can't keep putting features on top of broken code. that's what happened last time.

**Comment by Leon0315** [comment]
I tested on my windows machine, it says remote does not exist and can't push or pull

**Comment by cchampernowne** [comment]
debugging on windows today. Should I be leaving this in master, or do people want me to revert it?

**Comment by mdesco18** [comment]
Reverting this as there may be a common issue in where the new version of node doesn't use Windows users credentials properly with Nodegit

**Review by cchampernowne — DISMISSED** [review]

**Review by c-renard — DISMISSED** [review]
Approving now so if deemed necessary can revert right away

**Review by cchampernowne — APPROVED** [review]

**Review by c-renard — APPROVED** [review]

**Pull request merged**
