### PR TITLE
Fixed Issue #3: file editor overflows

### PR DESCRIPTION
**Pull request by AhmadAlsaif**
Fixed issue #3 by collapsing sequences of white space which makes lines break at newline characters. Also, fixed the alignment of the buttons by adding 10 more pixels to the hight and subtracting 2 pixels from the margins.

### CODE REVIEW

**Comment by SrishtiSinghal** [comment]
Could you change the margin properties into a short hand?

**Comment by HDeBoever** [comment]
The code behaved as intended when the window was resized on Ubuntu 16.04.

The code could do with some more commenting, but the logic is straight forward and understandable.

The formatting mirrored what was there previously, which is consistent with what one would expect.

Code is not redundant, and is required for the wanted behaviour. THe code is stand alone, and is likely not able to be replaced by library functions. Code had values hardcoded that were appropriate to he use case here.

No other issues were found during testing against master and the issue3_file_editor_overflows branch.

**Comment by AhmadAlsaif** [comment]
> Could you change the margin properties into a short hand?

Done!

**Review by HDeBoever — APPROVED** [review]
The code behaved as intended when the window was resized on Ubuntu 16.04.

The code could do with some more commenting, but the logic is straight forward and understandable.

The formatting mirrored what was there previously, which is consistent with what one would expect.

Code is not redundant, and is required for the wanted behaviour. THe code is stand alone, and is likely not able to be replaced by library functions. Code had values hardcoded that were appropriate to he use case here.

No other issues were found during testing against master and the issue3_file_editor_overflows branch.

**Review by mdesco18 — APPROVED** [review]
Code works on Windows 10 13-inch. The previous window sizing issues are still present but the commit-button class no longer has text overflow and stays consistent when resizing. 

Proper formatting and comments are clear to what was added and why. 

No library functions or variables needed.
No duplicate/redundant code.
No other issues.

Nice fix! add-stash adds more buttons and it should interact properly with this branch.

**Comment by SrishtiSinghal** [comment]
The code works as intended on macOS version 10.13.6 (17G5019) and has the correct logic. 

It is well documented with the correct formatting and commenting.

He implemented the suggested shorthand approach for margins thus reducing the 
duplicacy.

No library functions or variables needed.
No other issues found during testing.

**Comment by csamcharles** [comment]
Though this has been closed, just wanted to chime in that it works as expected on my machine as well (Windows 10 Pro). Good comments and coding style.

**Pull request merged**
