### PR TITLE
updated to node10, upgraded to electron 5, fixed errors and infinite …

### PR DESCRIPTION
**Pull request by smithmr**
## Steps to upgrade
1. use node v10.15.3 `nvm use 10`
2. delete node_modules and package-lock.json
3. in bash run `which python`
4. in bash run `npm config set python {result of which python}`
5. npm install

## Note
- You need to point npm config to python 2.7, so if you have both installed make sure you put the directory for python 2.7 in the `npm config set python` 

# Please test this out and post your errors if any below.

### CODE REVIEW

**Comment by smithmr** [comment]
## known issues
- changed files not appearing

**Comment by smithmr** [comment]
> ## known issues
> * changed files not appearing

## FIXED

**Review by Leon0315 — APPROVED** [review]
**Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.**
Yes, successfully upgraded to the new version, on mac os 10.14. Tested login, commit and push too remote.

**Is the code well documented? Would it be easily understood to other developers?**
yes, package updates don't need comments.

**Does it have correct linting/formatting?**
yes

**Is there any redundant or duplicate code? Any hard-coded values?**
no

**Can any of the code be replaced with library functions?**
N/A

**Are good names used for methods, variables, etc.? Do they follow naming conventions?**
yes

**Were any other issues found?**
found and solved.

**Review by jbenning97 — APPROVED** [review]
**Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.**
Yes, successfully upgraded to the new version, on mac os 10.13. Tested login, commit and stash.

**Is the code well documented? Would it be easily understood to other developers?**
yes, N/A in most places

**Does it have correct linting/formatting?**
yes

**Is there any redundant or duplicate code? Any hard-coded values?**
no

**Can any of the code be replaced with library functions?**
N/A

**Are good names used for methods, variables, etc.? Do they follow naming conventions?**
yes

**Were any other issues found?**
nope 👍

**Review by c-renard — APPROVED** [review]
**Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.**
Yes, on Windows 10 used the where command to find correct python path and after installing only python 2 on my machine the upgrade completed successfully. Tested editing files committing and pushing all successfully

**Is the code well documented? Would it be easily understood to other developers?**
Non required

**Does it have correct linting/formatting?**
Yes

**Is there any redundant or duplicate code? Any hard-coded values?**
No

**Can any of the code be replaced with library functions?**
N/A

**Are good names used for methods, variables, etc.? Do they follow naming conventions?**
Yes

**Were any other issues found?**
The issue outlined in original PR has been fixed

**Pull request merged**
