### PR TITLE
Issue20-Implement Oauth instead of storing credentials

### PR DESCRIPTION
**Pull request by Leon0315**
### Testing Procedure

-- click sign in with Github, it will redirect you to the GitHub log in page, login there and click authorize.
~~test open local repo, and make changes, commit and push.~~
-- test logout, click the sign out button, it opens a new window from Github, click the button and close the window, then you are signed out.

### Notes:
If you get a white electron window and in the console saying "connection refused" error, make sure you delete token.json from your folder (check if it was actually deleted), and  go to developers Tools -> Application ->clear storage -> clear site data, and refresh the app then you should be able to log in

### CODE REVIEW

**Comment by Leon0315** [comment]
I don't think people should test push in Oauth issue. The main implementation for oauth happens in `authenticate.ts`, as long as people can log in, the credential variable is valid. If push does not work, it must be something in `git.ts` is not working, and the only change from oauth implementation in `git.ts` is the credential variable. As long as people can log in and sign out, the oauth is good to go. What do you think? @mdesco18 @smithmr

**Review by jbenning97 — COMMENTED** [review]
Working signing in, signing out 👍 Tested on Mac. Will approve when confirmed on Windows

**Review by aujlarj — DISMISSED** [review]
Sign-in and Sign-out work on windows 10.

**Review by smithmr — CHANGES_REQUESTED** [review]
## Testing
I can sign in and sign out

## changes requested
- Error on my terminal that is related to an incomplete rebasing. This needs to be rebased properly before merging into master. These errors are new errors, the master branch does not have these errors.


Screen Shot 2019-06-20 at 8 06 35 PM

**Comment by mdesco18** [comment]
Nothing happens when I click the sign in button. This seems to be poorly merged. 
image

**Review by mdesco18 — APPROVED** [review]

**Comment by mdesco18** [comment]
Able to Sign in and out.  Oauth working fine now

**Review by jbenning97 — APPROVED** [review]

**Review by smithmr — APPROVED** [review]
## Merge conflicts now resolved.

**Pull request merged**
