### PR TITLE
Fix Issue 92: App crashes when pulling with no remote repositories

### PR DESCRIPTION
**Pull request by mdesco18**
Very simple fix. 
When pulling, checks if there is a directory for remote repositories. 
If not, pull fails.

### CODE REVIEW

**Review by cchampernowne — APPROVED** [review]
Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.
-Yes. tested locally on Windows 10. performs intended function and logic is sound
Is the code well documented? Would it be easily understood to other developers?
-yes. good comments explain the logic flow
code is documented for added code, however could maybe be more thorough
Does it have correct linting/formatting?
-yes
Is there any redundant or duplicate code? Any hard-coded values?
-no
Can any of the code be replaced with library functions?
-no
Are good names used for methods, variables, etc.? Do they follow naming conventions?
-yes
Were any other issues found?
-no

**Comment by smithmr** [comment]
Tested locally on MB PRO and am still getting the crash when pulling. 

I  would recommend also adding a check to not allow the person to pull if the branch is up to date.

Also, this branch needs to be rebased with master

**Review by smithmr — CHANGES_REQUESTED** [review]
Rebase with master. Also, ensure that you cannot pull if your branch is up to date. You can use getAheadBehind() once you rebase.

**Review by katland — APPROVED** [review]
**Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.**
The code does indeed correctly pop up the 'can not pull' error when trying to pull from a non-existant remote repository. I tested it on my mac OS version 10.13.6.
**Is the code well documented? Would it be easily understood to other developers?**
yes
**Does it have correct linting/formatting?**
yes
**Is there any redundant or duplicate code? Any hard-coded values?**
no
**Can any of the code be replaced with library functions?**
no
**Are good names used for methods, variables, etc.? Do they follow naming conventions?**
yes
**Were any other issues found?**
no

**Comment by katland** [comment]
@smithmr When testing the application and still having it crash, how many times did you run it? When I was testing the first time after I switched to the branch and ran npm start to test it, it crashed, but after restarting the program again it worked properly. Any time after that it has worked for me. It seems like the program doesn't necessarily reload completely on the first run in a different branch. Perhaps you've had a similar issue?

**Comment by smithmr** [comment]
@mdesco18 I changed the function in pull request to call checkIfExistOrigin instead because the way you were checking a file did not work on my machine.

**Review by smithmr — APPROVED** [review]

**Comment by mdesco18** [comment]
@smithmr I was literally just about to close this and rework your suggestion. Thanks for the initiative! Also, I meant to ask you. For the object that <getAheadBehind()> returns, is that an array of two numbers? two strings? I'd like to know how to properly check if I am ahead/behind for future.

**Pull request merged**
