### PR TITLE
Implement Issue 88: Display status of local repo

### PR DESCRIPTION
**Pull request by ajlarivi**
### Implements [issue 88](https://github.com/uvicgse/project-virtual-team-2/issues/88): Display status of local repo

**test cases:**
- local repo is up to date with remote: "Up to date" is displayed
- remote does not exist: "remote does not exist" is displayed
- local repo is ahead of remote: "your branch is x ahead of remote" is displayed
- local repo is behind the remote: "your branch is x behind remote" is displayed 

**note:** these all should update automatically, even if a commit is made from the command line outside of visualGit. An exception to this is if the if the local repo is behind the remote, you need to do either a git fetch from the command line or click the fetch button in visualGit for this to update.

### CODE REVIEW

**Comment by cchampernowne** [comment]
Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.
- currently says "remote does not exist" for the UTD with remote test case. tested locally on a freshly cloned-from-github branch. windows 10

Is the code well documented? Would it be easily understood to other developers?
- well documented and clear variable/function names. easily understood

Does it have correct linting/formatting?
- yes

Is there any redundant or duplicate code? Any hard-coded values?
- no. there are a few hard coded values used for formatting

Can any of the code be replaced with library functions?
- no

Are good names used for methods, variables, etc.? Do they follow naming conventions?
- yes

Were any other issues found?
- no

**Comment by cchampernowne** [comment]
Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.
- currently says "remote does not exist" for the UTD with remote test case. tested locally on a freshly cloned-from-github branch. windows 10

Is the code well documented? Would it be easily understood to other developers?
- well documented and clear variable/function names. easily understood
Does it have correct linting/formatting?
- yes

Is there any redundant or duplicate code? Any hard-coded values?
- no. there are a few hard coded values used for formatting

Can any of the code be replaced with library functions?
- no

Are good names used for methods, variables, etc.? Do they follow naming conventions?
- yes

Were any other issues found?
- no

**Comment by cchampernowne** [comment]
Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.
- currently says "remote does not exist" for the UTD with remote test case. tested locally on a freshly cloned-from-github branch. windows 10
Is the code well documented? Would it be easily understood to other developers?
- well documented and clear variable/function names. easily understood
Does it have correct linting/formatting?
- yes
Is there any redundant or duplicate code? Any hard-coded values?
- no. there are a few hard coded values used for formatting
Can any of the code be replaced with library functions?
- no
Are good names used for methods, variables, etc.? Do they follow naming conventions?
-yes
Were any other issues found?
- no

**Review by cchampernowne — APPROVED** [review]
Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.
- does not update in real-time when remote repo ahead of local. Does update when fetch button pressed 
- currently, fetch button does not fetch when behind remote, instead displays "local status utd" modal
- going from local branch ahead -> status utd worked as intended
- initially, all the code works. The issues arise in updating the status. I am going to approve, as these issues don't interfere with visualgits overall functionality

Is the code well documented? Would it be easily understood to other developers?
- well documented and clear variable/function names. easily understood

Does it have correct linting/formatting?
- yes

Is there any redundant or duplicate code? Any hard-coded values?
- no. there are a few hard coded values used for formatting

Can any of the code be replaced with library functions?
- no

Are good names used for methods, variables, etc.? Do they follow naming conventions?
- yes

Were any other issues found?
- no

**Review by smithmr — CHANGES_REQUESTED** [review]
It seems this is still not giving us the desired functionality.

Steps to reproduce:
1. edit test repo directly on github so that your branch is behind by 1 commit.
2. click git fetch
3. click git full
4. click git fetch

The status is still displaying that we are behind by 1 commit.

**Comment by ajlarivi** [comment]
> It seems this is still not giving us the desired functionality.
> 
> Steps to reproduce:
> 
> 1. edit test repo directly on github so that your branch is behind by 1 commit.
> 2. click git fetch
> 3. click git full
> 4. click git fetch
> 
> The status is still displaying that we are behind by 1 commit.

@smithmr for some reason I was under the impression that pull was just broken in visual git and being dealt with elsewhere but I'm not finding an issue for it. It should work as intended if you just do a pull from the command line. Will look into this tonight.

**Comment by smithmr** [comment]
> > It seems this is still not giving us the desired functionality.
> > Steps to reproduce:
> > 
> > 1. edit test repo directly on github so that your branch is behind by 1 commit.
> > 2. click git fetch
> > 3. click git full
> > 4. click git fetch
> > 
> > The status is still displaying that we are behind by 1 commit.
> 
> @smithmr for some reason I was under the impression that pull was just broken in visual git and being dealt with elsewhere but I'm not finding an issue for it. It should work as intended if you just do a pull from the command line. Will look into this tonight.

@ajlarivi I was not aware that pulling was broken, I will update my review

**Comment by smithmr** [comment]
> > > It seems this is still not giving us the desired functionality.
> > > Steps to reproduce:
> > > 
> > > 1. edit test repo directly on github so that your branch is behind by 1 commit.
> > > 2. click git fetch
> > > 3. click git full
> > > 4. click git fetch
> > > 
> > > The status is still displaying that we are behind by 1 commit.
> > 
> > 
> > @smithmr for some reason I was under the impression that pull was just broken in visual git and being dealt with elsewhere but I'm not finding an issue for it. It should work as intended if you just do a pull from the command line. Will look into this tonight.
> 
> @ajlarivi I was not aware that pulling was broken, I will update my review

**Review by smithmr — APPROVED** [review]

**Review by aujlarj — COMMENTED** [review]
**Does the code work?** Yes
**Did I test it locally?** Yes
**What OS am I using?** Windows 10
**Does it perform its intended function, the logic is correct, etc.**
I do see the Fetch and Local Status interface. Don't really know how to test it. 
I wasn't able to push. it says "git push --set-upstream origin test-branch" which I did but still wasn't able to push 
**Is the code well documented? Would it be easily understood to other developers?**
Yes, the comments are added where ever necessary 
**Does it have correct linting/formatting?**
The formate looks good.
**Is there any redundant or duplicate code? Any hard-coded values?**
I didn't find any duplicate code.
**Can any of the code be replaced with library functions?**
N/A
**Are good names used for methods, variables, etc.? Do they follow naming conventions?**
Yes
Yes, the variables are reused and new ones are named accordingly
**Were any other issues found?**
Not related to this issue.

**Pull request merged**
