### PR TITLE
Hotfix Issue 2: Improper newline formatting in diff panel

### PR DESCRIPTION
**Pull request by mdesco18**
Implemented because of issue #104 
Hotfix for issue #2 

Removes unnecessary lines at end of diff in diff panel of modified files

**Test:** Click on a modified file in the file-panel and the diff-panel should no longer have the text "no newline at end of file"

### CODE REVIEW

**Review by jbenning97 — APPROVED** [review]
**Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.** 
Yes the code works. Tested on macOS 10.13

**Is the code well documented? Would it be easily understood to other developers?**

Yes

**Does it have correct linting/formatting?**

 Yes

**Is there any redundant or duplicate code? Any hard-coded values?** 

No, there were not redundant or duplicate code. 

**Can any of the code be replaced with library functions?** 

No

**Are good names used for methods, variables, etc.? Do they follow naming conventions?** 

Yes

**Were any other issues found?** - I did not find any other issues during my testing.

**Comment by sinoyuhanxiao** [comment]
**Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.**
The code works, I tested that on Windows 10. It performs the intended function with correct logic as it removes unnecessary lines. 
**Is the code well documented? Would it be easily understood to other developers?**
Yes they are well documented and can be understood.
**Does it have correct linting/formatting?**
Yes
**Is there any redundant or duplicate code? Any hard-coded values?**
No redundant and hard codes
**Can any of the code be replaced with library functions?**
No
**Are good names used for methods, variables, etc.? Do they follow naming conventions?**
Yes all followed conventions
**Were any other issues found?**
No other issues found

**Review by sinoyuhanxiao — APPROVED** [review]

**Review by csamcharles — APPROVED** [review]
Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.
Code works as expected on Windows 10 Pro.

Is the code well documented? Would it be easily understood to other developers?

Yes

Does it have correct linting/formatting?

Yes

Is there any redundant or duplicate code? Any hard-coded values?

No, simple bug fix.

Can any of the code be replaced with library functions?

No

Are good names used for methods, variables, etc.? Do they follow naming conventions?

Yes

Were any other issues found? None

**Comment by csamcharles** [comment]
good to merge @mdesco18 👍

**Pull request merged**
