### PR TITLE
Show most recent repositories, Fixes #7

### LINKED ISSUE #7: Feature request: Show most recent repositories
Implement a feature into VisualGit which shows the users most recent (maybe recent 5?) opened repositories, and lets them open them.

### PR DESCRIPTION
**Pull request by AhmadAlsaif**
We have implemented a new feature which shows the user's most recent opened repositories

Screen Shot 1440-09-21 at 7 09 32 PM

Every time a user opens a new repository, the system appends opened repo path into recent_repos.json file. If recent_repos.json does not exist, it gets created before appending repo path.

### CODE REVIEW

**Review by zeshili — APPROVED** [review]
- **Does the code work?** Yes, the code works as expected for me.
- **Is the code well documented?** Yes, the code has extensive documentation that makes it easy to understand the code. 
- **Does it have correct linting/formatting?** Yes, the code has correct formatting. 
- **Is there any redundant or duplicate code? Any hard-coded values?** No, the code does include any redundant or duplicated code. 
- **Can any of the code be replaced with library functions?** No, the code actually uses a lot of Angular built in functions. 
- **Are good names used for methods, variables, etc.? Do they follow naming conventions?** Yes, the functions and variable names are appropriate. 
- **Were any other issues found?** No issues were found related to this code. 

Looks good.

**Review by mdesco18 — APPROVED** [review]
**Does the code work?** Yes. Works as intended.
**Is the code well documented?** Yes. Describes the functions added clearly and concisely. 
**Does it have correct linting/formatting?** Yes. 
**Is there any redundant or duplicate code?** Any hard-coded values? No
**Can any of the code be replaced with library functions?** No it makes use of newly created functions
**Are good names used for methods, variables, etc.? Do they follow naming conventions?** Yes, follows the original code well. 
**Were any other issues found?**
I'm not able to access my recent repos without going fullscreen as there is no scroll feature. Not sure if this is due to styling or the resolution of VisualGit on my machine but I have no settings set that would cause this to happen. May be a future issue. 
recentrepos

**Comment by jamshale** [comment]
> **Does the code work?** Yes. Works as intended.
> **Is the code well documented?** Yes. Describes the functions added clearly and concisely.
> **Does it have correct linting/formatting?** Yes.
> **Is there any redundant or duplicate code?** Any hard-coded values? No
> **Can any of the code be replaced with library functions?** No it makes use of newly created functions
> **Are good names used for methods, variables, etc.? Do they follow naming conventions?** Yes, follows the original code well.
> **Were any other issues found?**
> I'm not able to access my recent repos without going fullscreen as there is no scroll feature. Not sure if this is due to styling or the resolution of VisualGit on my machine but I have no settings set that would cause this to happen. May be a future issue.
> recentrepos

The problem of not being able to see all the DOM elements is another issue in my opinion

**Comment by jamshale** [comment]
The problem of not being able to see all the DOM elements is a separate issue in my opinion. The page has scrolling and zooming disabled and no media queries for smaller screen sizes. I don't think we should have to try and accommodate the design to work around this issue. If you open visualgit on a desktop size display it looks good. The page had major issues at smaller screen sizes before trying to add any DOM elements to the page. I think scrolling, zooming or media queries need to be implemented for the project to succeed with smaller screen sizes.

image

**Comment by HDeBoever** [comment]
I just approved the merge. Issue 7 can now be deleted as it has been consumed by the master branch.

**Comment by csamcharles** [comment]
I see that this has now been closed, but just wanted to say that it works on my machine as well as expected - confirming what others have said. Nice work on the front-end as well 💯 looks great.

**Pull request merged**
