### PR TITLE
Fix Issue #9: Navbar Icons Adjusting Irregularly 

### PR DESCRIPTION
**Pull request by jbenning97**
The icons on the navbar were unnecessarily adjusting themselves on hover and at times, on window resize. In addition to fixing this, I have made the entire navbar more responsive by making some improvements to its DOM structure and added the stash icon.

### CODE REVIEW

**Review by zhihaoxu26 — COMMENTED** [review]
The solution is great. Now, the icons only move to the second row when I resize the window. It's perfect on Mac now.

**Review by zhihaoxu26 — APPROVED** [review]

**Review by mdesco18 — APPROVED** [review]
**Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.**
Looks and works great; even when recent repository path name is large. Using Windows 10 13-inch screen.
**Is the code well documented? Would it be easily understood to other developers?**
It is not documented. However, it would be easily understood by those familiar with HTML
**Does it have correct linting/formatting?**
Follows the format well
**Is there any redundant or duplicate code? Any hard-coded values?**
No
**Can any of the code be replaced with library functions?**
N/A
**Are good names used for methods, variables, etc.? Do they follow naming conventions?**
For the newly added buttons, yes. Otherwise, N/a
**Were any other issues found?**
No, however, dropdown menu and most buttons in navbar still non-functioning

**Review by aujlarj — APPROVED** [review]
**Does the code work?** Yes
**Did I test it locally?**  Yes
**What OS am I using?** Windows 10
**Does it perform its intended function, the logic is correct etc.**
Looks great. Resizing put the buttons in the second row
**Is the code well documented? Would it be easily understood to other developers?**
It is not documented. I am pretty new to HTML/webdev so it did take me time to understanding everything
**Does it have correct linting/formatting?**
The formate looks good.
**Is there any redundant or duplicate code? Any hard-coded values?**
I didn't find any duplicate code.
**Can any of the code be replaced with library functions?**
N/A
**Are good names used for methods, variables, etc.? Do they follow naming conventions?**
Yes, the variables(id, class, button, etc) are named accordingly
**Were any other issues found?**
Nope, everything adjusted accordingly on resizing.

**Comment by aujlarj** [comment]
I just noticed one thing with Nav bar. When we 'Continue without sign in' and then try to sign in after. The credential(username and password) textbox appears on top of another button. 
I think it's ok as we won't be using those button while we are signing-in and after the sign-in it does go into the corner.

**Before Sign In:**
image

**After Sign In:**
image

**Comment by jbenning97** [comment]
> I just noticed one thing with Nav bar. When we 'Continue without sign in' and then try to sign in after. The credential(username and password) textbox appears on top of another button.
> I think it's ok as we won't be using those button while we are signing-in and after the sign-in it does go into the corner.
> 
> **Before Sign In:**
> image
> 
> **After Sign In:**
> image

I will make this into a new issue. Good catch!

**Pull request merged**
